app:
  jwtExpirationInMs: '604800000'
  jwtSecret: ${JWT_SIGNING_KEY}
logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  port: '8085'
  ssl.key-store-type: 'PKCS12'
  ssl.key-store: '/etc/stempol/certs/keystore.p12'
  ssl.key-store-password: ${KEYSTORE_PASS}
  ssl.key-alias: 'tomcat'
  ssl.keyStoreType: PKCS12
  ssl.enabled-protocols: TLSv1.2,TLSv1.3
security.require-ssl: true
spring:
  ldap:
    embedded:
      base-dn: dc=politie,dc=nl
      ldif: classpath:localldapactivedirectory.ldif
      port: 12345
      validation:
        enabled: false
