app:
  jwtExpirationInMs: '604800000'
  jwtSecret: JWTSuperSecretKey
logging:
  level:
    org:
      hibernate:
        SQL: INFO
server:
  port: '8085'
  ssl.key-store-type: 'PKCS12'
  ssl.key-store: '/etc/stempol/certs/keystore.p12'
  ssl.key-store-password: 'zdC3MZNQ4CPBB89mZZ5dwUs6PUJN72R9'
  ssl.key-alias: 'tomcat'
  ssl.keyStoreType: PKCS12
security.require-ssl: true
spring:
  ldap:
    embedded:
      base-dn: dc=politie,dc=nl
      ldif: classpath:localldapactivedirectory.ldif
      port: 12345
      validation:
        enabled: false
